### ISSUE TITLE
Deblender sometimes fails to model second object, or crashes

### ISSUE THREAD

**Issue by lorena21395** [fred3m/scarlet#26]
Hi,
I am currently using Galsim to create images of two galaxies and then using deblender to create a model of the two. I enter the true coordinates of the two objects when I create the sources, and although a model is created for both objects, sometimes the second one is empty (as shown in image below).
![figure_1](https://user-images.githubusercontent.com/31394370/35122662-8e52a3dc-fc6d-11e7-995c-914e47514930.png)

This is how I run the deblender. Note that img is the original image created by Galsim and coords are the coordinates of the two objects in the original. I am using bg_rms = 100.

```
def make_model(img,bg_rms,B,coords):
    #constraints on morphology:                                                   
    # "S": symmetry                                                               
    # "m": monotonicity (with neighbor pixel weighting)                           
    # "+": non-negativity                                                         
    constraints = {"S": None, "m": {'use_nearest': False}, "+": None}

    # initial size of the box around each object                                  
    # will be adjusted as needed                                                  
    shape = (B, 15, 15)
    sources = [scarlet.Source(coord, shape, constraints=constraints) for coord in\
 coords]
    blend = scarlet.Blend(sources, img, bg_rms=[bg_rms])
    # if you have per-pixel weights:                                              
    #weights = np.empty((B,Ny,Nx))                                                
    #blend = scarlet.Blend(sources, img, bg_rms=bg_rms, weights=weights)          

    # if you have per-band PSF kernel images:                                     
    # Note: These need to be difference kernels to a common minimum               
    #pdiff = [PSF[b] for b in range(B)]                                           
    #psf = scarlet.transformations.GammaOp(shape, pdiff)                          
    #blend = scarlet.Blend(sources, img, bg_rms=bg_rms, psf=psf)                  
    # run the fitter for 200 steps (or until convergence)                         

    blend.fit(200)#, e_rel=1e-1)                                                  
    # render the multi-band model: has same shape as img                          
    model = blend.get_model()
    mod2 = blend.get_model(m=1)
    return model,mod2
```

The second issue I am having is that sometimes the code crashes with a ValueError or numpy.linalg.linalg.LinAlgError (shown below). Thanks in advance for your help!

ValueError
```
/Users/lorena/anaconda3/lib/python3.6/site-packages/proxmin-0.4.3-py3.6.egg/proxmin/operators.py:37: RuntimeWarning: invalid value encountered in true_divide
/Users/lorena/anaconda3/lib/python3.6/site-packages/scarlet-0.1.d2e9b44-py3.6-macosx-10.7-x86_64.egg/scarlet/source.py:149: RuntimeWarning: invalid value encountered in less
  morph[morph<0] = 0
/Users/lorena/anaconda3/lib/python3.6/site-packages/scarlet-0.1.d2e9b44-py3.6-macosx-10.7-x86_64.egg/scarlet/source.py:161: RuntimeWarning: invalid value encountered in greater
  ypix, xpix = np.where(morph>blend._bg_rms[band]/2)
/Users/lorena/anaconda3/lib/python3.6/site-packages/scarlet-0.1.d2e9b44-py3.6-macosx-10.7-x86_64.egg/scarlet/source.py:163: RuntimeWarning: invalid value encountered in greater
  ypix, xpix = np.where(morph>0)
Traceback (most recent call last):
  File "galsim_deblend.py", line 194, in <module>
    model,mod2 = make_model(img,bg_rms,B,coords)
  File "galsim_deblend.py", line 80, in make_model
    blend = scarlet.Blend(sources, img, bg_rms=bg_rms)
  File "/Users/lorena/anaconda3/lib/python3.6/site-packages/scarlet-0.1.d2e9b44-py3.6-macosx-10.7-x86_64.egg/scarlet/blend.py", line 76, in __init__
    self.init_sources()
  File "/Users/lorena/anaconda3/lib/python3.6/site-packages/scarlet-0.1.d2e9b44-py3.6-macosx-10.7-x86_64.egg/scarlet/blend.py", line 255, in init_sources
    self.sources[m].init_source(self, self._img)
  File "/Users/lorena/anaconda3/lib/python3.6/site-packages/scarlet-0.1.d2e9b44-py3.6-macosx-10.7-x86_64.egg/scarlet/source.py", line 579, in init_source
    self.init_func(self, blend, img)
  File "/Users/lorena/anaconda3/lib/python3.6/site-packages/scarlet-0.1.d2e9b44-py3.6-macosx-10.7-x86_64.egg/scarlet/source.py", line 164, in init_templates
    Ny = np.max(ypix)-np.min(ypix)
  File "/Users/lorena/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2272, in amax
    out=out, **kwargs)
  File "/Users/lorena/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity
```

LinAlgError
```
/Users/lorena/anaconda3/lib/python3.6/site-packages/proxmin-0.4.3-py3.6.egg/proxmin/utils.py:340: RuntimeWarning: divide by zero encountered in double_scalars
/Users/lorena/anaconda3/lib/python3.6/site-packages/proxmin-0.4.3-py3.6.egg/proxmin/utils.py:340: RuntimeWarning: invalid value encountered in multiply
/Users/lorena/anaconda3/lib/python3.6/site-packages/proxmin-0.4.3-py3.6.egg/proxmin/utils.py:310: RuntimeWarning: divide by zero encountered in double_scalars
/Users/lorena/anaconda3/lib/python3.6/site-packages/proxmin-0.4.3-py3.6.egg/proxmin/utils.py:310: RuntimeWarning: invalid value encountered in multiply
/Users/lorena/anaconda3/lib/python3.6/site-packages/proxmin-0.4.3-py3.6.egg/proxmin/utils.py:358: RuntimeWarning: divide by zero encountered in double_scalars
/Users/lorena/anaconda3/lib/python3.6/site-packages/proxmin-0.4.3-py3.6.egg/proxmin/utils.py:360: RuntimeWarning: divide by zero encountered in double_scalars
/Users/lorena/anaconda3/lib/python3.6/site-packages/proxmin-0.4.3-py3.6.egg/proxmin/utils.py:360: RuntimeWarning: invalid value encountered in true_divide
Traceback (most recent call last):
  File "galsim_deblend.py", line 194, in <module>
    model,mod2 = make_model(img,bg_rms,B,coords)
  File "galsim_deblend.py", line 92, in make_model
    blend.fit(200)#, e_rel=1e-1)
  File "/Users/lorena/anaconda3/lib/python3.6/site-packages/scarlet-0.1.d2e9b44-py3.6-macosx-10.7-x86_64.egg/scarlet/blend.py", line 229, in fit
    e_rel=self._e_rel, e_abs=self._e_abs, accelerated=accelerated, traceback=traceback)
  File "/Users/lorena/anaconda3/lib/python3.6/site-packages/proxmin-0.4.3-py3.6.egg/proxmin/algorithms.py", line 487, in bsdmm
  File "/Users/lorena/anaconda3/lib/python3.6/site-packages/scarlet-0.1.d2e9b44-py3.6-macosx-10.7-x86_64.egg/scarlet/blend.py", line 541, in _steps_f
    self._stepAS = [self._cbAS[block](block) for block in [0,1]]
  File "/Users/lorena/anaconda3/lib/python3.6/site-packages/scarlet-0.1.d2e9b44-py3.6-macosx-10.7-x86_64.egg/scarlet/blend.py", line 541, in <listcomp>
    self._stepAS = [self._cbAS[block](block) for block in [0,1]]
  File "/Users/lorena/anaconda3/lib/python3.6/site-packages/proxmin-0.4.3-py3.6.egg/proxmin/utils.py", line 222, in __call__
  File "/Users/lorena/anaconda3/lib/python3.6/site-packages/scarlet-0.1.d2e9b44-py3.6-macosx-10.7-x86_64.egg/scarlet/blend.py", line 486, in _one_over_lipschitz
    LA = np.real(np.linalg.eigvals(SSigma_1S).max())
  File "/Users/lorena/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 889, in eigvals
    _assertFinite(a)
  File "/Users/lorena/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 217, in _assertFinite
    raise LinAlgError("Array must not contain infs or NaNs")
numpy.linalg.linalg.LinAlgError: Array must not contain infs or NaNs
```

**Comment by lorena21395** [comment]
Additional note. The code crashes about 2/3 of the time with one of those two errors and the second object doesn't appear ~10% of the time.

**Comment by fred3m** [comment]
I can't say for sure without running scarlet on the images, but my guess would be that you are using a value for `bg_rms` that is much too high. Looking at your images, `bg_rms=100` looks to be way too high. scarlet uses the `bg_rms` to essentially set a cutoff, ignoring flux below `bg_rms/2`. So you are likely cutting out most (if not all) of the flux from one of your objects.

What type of noise model did you use for galsim? For example if you used poison noise with `sky_level=10`, then you should set `bg_rms=10`. Looking at your images I'm guessing that bg_rms should be somewhere around `20-50`.

**Comment by lorena21395** [comment]
I also tried bg_rms = 10 and it didn't do much better. I am currently using guassian noise.

```
noise = np.random.normal(scale=bg_rms,size=(dims[0],dims[1]))
im += noise
```

**Comment by fred3m** [comment]
Can you attach a sample image that is giving you problems? I'd like to see if I can replicate the problem and diagnose it.

**Comment by pmelchior** [comment]
I think the centering goes off rails. I've seen this a fair bit too, so I patched it recently (but the branch isn't merged yet). Let me give this a proper test tomorrow.

**Comment by pmelchior** [comment]
Yes and yes

**Comment by esheldon** [comment]
Then based on the image Lorena posted I don't think bg_rms was too high;
those are very high s/n objects.

**Comment by pmelchior** [comment]
neither do I. Again, I think the centroid wanders off, then the component gets set to zero (because there's nothing to fit at its new location), and then LinAlg balks because some matrices become singular.

**Comment by fred3m** [comment]
Looking at the traceback that Lorena posted, the `ValueError` occurs during initialization because there are no pixels above `bg_rms/2` for one of the sources. So either the peak positions are incorrect (are x and y flipped? scarlet wants positions in (y,x) ) or the source has no flux above `bg_rms/2`. We should add a check to prevent this from happening, or at the very least produce a more useful error message, but low flux centered on the coordinates given is the cause of this error.

Since you are using the true coordinates you can also test if re-centering is causing the other issue by turning it off using
```
sources = [scarlet.Source(coord, shape, constraints=constraints, shift_center=0) for coord in coords]
```

But if Lorena can post an image that has a `ValueError` on initialization and another that produces a `LinAlgError` (and the coordinates that she is using for both of them) then I can test it myself and find the problem.

**Comment by lorena21395** [comment]
@fred3m Here are the images you asked for. They are 50x50 pixels. Let me know if you would prefer a different file type. 

LinAlgError with coordinates (24.5, 24.5), (25.705679379667469, 36.439277081693206)
![linalg_image](https://user-images.githubusercontent.com/31394370/35136046-183c5930-fcaf-11e7-8583-ddb3ef98adaa.png)


ValueError with coordinates (24.5, 24.5), (36.050461807131782, 27.753741237712376)
![valerr_image](https://user-images.githubusercontent.com/31394370/35136088-5aecb806-fcaf-11e7-8a25-35b0f30b71ff.png)

**Comment by esheldon** [comment]
Lorena, I had a look at your code and I think Fred is correct
```python
    dx2,dy2 = 12.0*np.cos(theta),12.0*np.sin(theta)
    coord1 = (dx1+(dims[0]-1.)/2.,dy1+(dims[1]-1.)/2.)
    coord2 = (dx2+(dims[0]-1.)/2.,dy2+(dims[1]-1.)/2.)
    coords = [coord1,coord2]
    gal1 = gal1.shift(dx=dx1, dy=dy1)
    gal2 = gal2.shift(dx=dx2, dy=dy2)
```
In numpy and scarlet, coordinate order is (y,x) not (x,y) so it should be
```python
    dy2,dx2 = 12.0*np.cos(theta),12.0*np.sin(theta)
    coord1 = (dy1+(dims[0]-1.)/2.,dx1+(dims[1]-1.)/2.)
    coord2 = (dy2+(dims[0]-1.)/2.,dx2+(dims[1]-1.)/2.)
    coords = [coord1,coord2]
    gal1 = gal1.shift(dx=dx1, dy=dy1)
    gal2 = gal2.shift(dx=dx2, dy=dy2)
```
I'm actually pretty impressed that the code sometimes found the right center despite this!

**Comment by pmelchior** [comment]
Well, if the source model is large enough to have flux at the actual location of the source, the centroid updates will work just fine. It'll take a few dozen iterations but it'll get there.

However, we should make sure people understand that we're using the y/x convention for all coordinates.

**Comment by lorena21395** [comment]
I switched the coordinates and everything works now. Thank you for your help.

**Comment by fred3m** [comment]
No problem, we've added a warning to the README file so that the coordinate ordering is more clear. Thanks for the feedback!
