### ISSUE TITLE
Issues with proxmin in blend.py?

### ISSUE THREAD

**Issue by herjy** [fred3m/scarlet#67]
When running scarlet on a typical example such as the one provided in the documentation, the script crashes with the following error:

I fixed it to make it execute in my version by replacing line 193 of blend.py by:

converged = res

```
Traceback (most recent call last):
  File "/Users/remy/Desktop/LSST_Deblending/Test_scarlet.py", line 35, in <module>
    blend.fit(200)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scarlet-0.3.b34b32b-py2.7-macosx-10.6-intel.egg/scarlet/blend.py", line 193, in fit
    converged, error = res
ValueError: too many values to unpack
```

**Comment by herjy** [comment]
You are right, The last version of proxmin was not pulled on the right environment. 
Now it works with the updated versions.
My bad.

**Comment by fred3m** [comment]
No worries. I'm sure that you'll find a number of bugs in the next few weeks, I'm just glad this wasn't one of them.
